# Generated by Django 5.2.17 on 2026-09-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20260925_0017'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailyentry',
            new_name='accounts_da_office__3fa152_idx',
            old_name='accounts_da_office__b3d7c7_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyentry',
            new_name='accounts_da_entry_t_0e5e0f_idx',
            old_name='accounts_da_entry_t_5f2c4b_idx',
        ),
    ]
