# Generated by Django 5.2.17 on 2026-09-25 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_guide', '0002_botpressconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotpressConfig',
        ),
    ]
