# Generated by Django 5.2.17 on 2026-09-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_dailyentry_options_alter_office_options'),
        ('accounts', '0002_staffprofile'),
    ]

    operations = [
    ]
