# Generated by Django 5.2.17 on 2026-09-24 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyentry',
            options={'ordering': ['-entry_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['name']},
        ),
    ]
