# Generated by Django 5.2.17 on 2026-09-24 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_accounts_da_office__b3d7c7_idx_accounts_da_office__3fa152_idx_and_more'),
        ('accounts', '0004_stable_dailyentry_indexes'),
    ]

    operations = [
    ]
